// DbgEventProxy.idl : IDL source for DbgEventProxy.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (DbgEventProxy.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(15BF663A-6699-42C9-B779-F517593BF52A),
	version(1.0),
	helpstring("DbgEventProxy 1.0 Type Library")
]
library DBGEVENTPROXYLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		object,
		uuid(1E046966-B6C4-42D8-8ADD-62C60557364D),
		dual,
		helpstring("IEventCallbacksProxy Interface"),
		pointer_default(unique)
	]
	interface IEventCallbacksProxy : IDispatch
	{
		[id(1), helpstring("method CreateIDebugEventCallbacks")] HRESULT CreateIDebugEventCallbacks([in] ULONG InterestMask, [out, retval] IUnknown** IDebugEventCallbacksPtr);
	};

	[
		uuid(D91C6B84-05C8-4B67-87DF-FACDE927C951),
		helpstring("_IEventCallbacksProxyEvents Interface")
	]
	dispinterface _IEventCallbacksProxyEvents
	{
		properties:
		methods:
		[id(1)] HRESULT Breakpoint([in] unsigned __int64 Offset, [in] unsigned long Id, [in] unsigned long BreakType, [in] unsigned long ProcType, [in] unsigned long Flags, [in] unsigned long DataSize, [in] unsigned long DataAccessType, [in] unsigned long PassCount, [in] unsigned long CurrentPassCount, [in] unsigned long MatchThread, [in] unsigned long CommandSize, [in] unsigned long OffsetExpressionSize);
		[id(2)] HRESULT Exception([in] unsigned long ExceptionCode, [in] unsigned long ExceptionFlags, [in] unsigned __int64 ExceptionRecord, [in] unsigned __int64 ExceptionAddress, [in] unsigned long NumberParameters, [in] unsigned __int64 ExceptionInformation0, [in] unsigned __int64 ExceptionInformation1, [in] unsigned __int64 ExceptionInformation2, [in] unsigned __int64 ExceptionInformation3, [in] unsigned __int64 ExceptionInformation4, [in] unsigned __int64 ExceptionInformation5, [in] unsigned __int64 ExceptionInformation6, [in] unsigned __int64 ExceptionInformation7, [in] unsigned __int64 ExceptionInformation8, [in] unsigned __int64 ExceptionInformation9, [in] unsigned __int64 ExceptionInformation10, [in] unsigned __int64 ExceptionInformation11, [in] unsigned __int64 ExceptionInformation12, [in] unsigned __int64 ExceptionInformation13, [in] unsigned __int64 ExceptionInformation14, [in] unsigned long FirstChance );
		[id(3)] HRESULT CreateThread([in]  unsigned __int64 Handle,[in] unsigned __int64 DataOffset,[in] unsigned __int64 StartOffset );
		[id(4)] HRESULT ExitThread([in]  unsigned long ExitCode );
		[id(5)] HRESULT CreateProcess([in]  unsigned __int64 ImageFileHandle,[in] unsigned __int64 Handle,[in] unsigned __int64 BaseOffset,[in] unsigned long ModuleSize,[in,optional] const char* ModuleName,[in,optional] const char* ImageName,[in,optional] unsigned long CheckSum,[in,optional] unsigned long TimeDateStamp,[in,optional] unsigned __int64 InitialThreadHandle,[in,optional] unsigned __int64 ThreadDataOffset,[in,optional] unsigned __int64 StartOffset );
		[id(6)] HRESULT ExitProcess([in]  unsigned long ExitCode );
		[id(7)] HRESULT LoadModule([in]  unsigned __int64 ImageFileHandle,[in] unsigned __int64 BaseOffset,[in] unsigned long ModuleSize,[in,optional] const char* ModuleName,[in,optional] const char* ImageName,[in,optional] unsigned long CheckSum,[in,optional] unsigned long TimeDateStamp );
		[id(8)] HRESULT UnloadModule([in,optional]  const char* ImageBaseName,[in,optional] unsigned __int64 BaseOffset );
		[id(9)] HRESULT SystemError([in]  unsigned long Error,[in] unsigned long Level );
		[id(10)] HRESULT SessionStatus([in]  unsigned long Status );
		[id(11)] HRESULT ChangeDebuggeeState([in]  unsigned long Flags,[in] unsigned __int64 Argument );
		[id(12)] HRESULT ChangeEngineState([in]  unsigned long Flags,[in] unsigned __int64 Argument );
		[id(13)] HRESULT ChangeSymbolState([in]  unsigned long Flags,[in] unsigned __int64 Argument );
	};

	[
		uuid(2733E71F-DC8F-4882-BC65-83D254072CC3),
		helpstring("EventCallbacksProxy Class")
	]
	coclass EventCallbacksProxy
	{
		[default] interface IEventCallbacksProxy;
		[default, source] dispinterface _IEventCallbacksProxyEvents;
	};

	[
		object,
		uuid(A6261673-4D6C-4355-8DAA-8F24D5789D07),
		dual,
		helpstring("IOutputCallbacksProxy Interface"),
		pointer_default(unique)
	]
	interface IOutputCallbacksProxy : IDispatch
	{
		[id(1), helpstring("method CreateIDebugOutputCallbacks")] HRESULT CreateIDebugOutputCallbacks([out, retval] IUnknown** IDebugOutputCallbacksPtr);
	};

	[
		uuid(961A014D-C67A-4374-A7CA-EA844ADC982E),
		helpstring("_IOutputCallbacksProxyEvents Interface")
	]
	dispinterface _IOutputCallbacksProxyEvents
	{
		properties:
		methods:
		[id(1)] HRESULT Output([in] unsigned long Mask, [in] const char* Text);
	};

	[
		uuid(AA9A2EA2-4B17-495C-81BE-891079C2E293),
		helpstring("OutputCallbacksProxy Class")
	]
	coclass OutputCallbacksProxy
	{
		[default] interface IOutputCallbacksProxy;
		[default, source] dispinterface _IOutputCallbacksProxyEvents;
	};
};
